### ISSUE TITLE
Go-Live Checklist 

### ISSUE THREAD

**Issue by karlpauls** [hlxsites/sazerac-wheatleyvodka#117]
## Before Go-Live

- [x] [Content and Design QA](https://www.hlx.live/docs/go-live-checklist#content-and-design-qa)

Make sure that your content and design conforms to the specifications and that you are happy with the website you see on your projects .hlx.live domain. This may include checks for specific accessibility and SEO requirements of your project.

- [x] [Performance Validation](https://www.hlx.live/docs/go-live-checklist#performance-validation)

Every Franklin project should produce a lighthouse score of 100 for mobile and desktop from [Google Pagespeed insights](https://pagespeed.web.dev/) on its respective .hlx.live site.

See the document [Keeping it 100, Web Performance with Franklin](https://www.hlx.live/developer/keeping-it-100) for more information.

- [x] [Analytics Validation](https://www.hlx.live/docs/go-live-checklist#analytics-validation)

Make sure that all your analytics setup and the rest of your martech stack is firing as expected and visitor data is visible in your reporting dashboards.

- [x] [Legacy Redirects](https://www.hlx.live/docs/go-live-checklist#legacy-redirects)

In most migrations there are legacy URLs that are retired. Make sure those are reflected in your redirects spreadsheet (redirects.xlsx in sharepoint or redirects in google), found in your project content folder.

See the document [Redirects](https://www.hlx.live/docs/redirects) for more information.

- [x] [Sitemap & Robots](https://www.hlx.live/docs/go-live-checklist#sitemap--robots)

For most websites with a significant number of pages, a sitemap is desirable. Franklin automatically generates those from the query index.

If you have a sitemap that’s generated for your site make sure it is discoverable from your robots.txt. ​​

Note: hlx.page and hlx.live are kept hidden from crawlers intentionally, to avoid duplicate content.

See the documents [Indexing](https://www.hlx.live/developer/indexing) and [Sitemaps](https://www.hlx.live/developer/sitemap) for more information.

- [x] [Favicon](https://www.hlx.live/docs/go-live-checklist#favicon)

Adding a favicon to your site gives it a professional look in your visitor’s browsers.

See the document [Favicon](https://www.hlx.live/developer/favicon) for more information.

- [x] [CDN Configuration](https://www.hlx.live/docs/go-live-checklist#cdn-configuration)

Please see the following BYOD setup documentation for more information.

[Custom domains without a custom CDN](https://www.hlx.live/docs/byo-dns)

[Push Invalidation Setup](https://www.hlx.live/docs/go-live-checklist#push-invalidation-setup)

- [x] Make sure push invalidation is properly set up according to the document. As we can not test the setup by publishing a small change and verifying that the change is visible on the production domain until the go-live with the dns switch, that test is added to the post go-live.

- [x] [Update Production Host](https://www.hlx.live/docs/go-live-checklist#update-production-host)

After setting up your production CDN, add the host property to the sidekick configuration in /tools/sidekick/config.json in your github repo, to allow your authors to navigate directly from the production domain to edit directly from the sidekick.

See the document [Sidekick Configuration](https://www.hlx.live/docs/sidekick#customizing-the-sidekick) for more information.
