### ISSUE TITLE
Post Go-Live Checklist

### ISSUE THREAD

**Issue by karlpauls** [hlxsites/sazerac-wheatleyvodka#120]
## Post Go-Live Validation

- [x] [Push Invalidation Setup](https://www.hlx.live/docs/go-live-checklist#push-invalidation-setup)

 As we can not test the setup by publishing a small change and verifying that the change is visible on the production domain until the go-live with the dns switch, that test is added to the post go-live.

- [x] [Performance Validation](https://www.hlx.live/docs/go-live-checklist#performance-validation-1)

Validate that the performance is still at a lighthouse score of 100 via [pagespeed insights](https://pagespeed.web.dev/) on the production environment. Introducing a CDN layer can have adverse performance effects that are usually visible on the protocol layer. Typical culprits are running HTTP/1.1 or ineffective origin caching as well as bot detection or other libraries injected by the CDN configuration.

- [x] [Google Search Console](https://www.hlx.live/docs/go-live-checklist#google-search-console)

If you have an active Google Search Console with your sitemap uploaded, it may be valuable to get a coverage report and make sure that indexing works as expected. The Google Search Console should be monitored for the weeks after a go-live.

- [x] [404 Report](https://www.hlx.live/docs/go-live-checklist#report)

After a website has been migrated there is usually a set of 404 Not Founds, which should be monitored after the go-live and redirected to popular page URLs. This information can be pulled from your site analytics and the respective Franklin bot report. Monitoring this for the weeks after a go-live is recommended.
